version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    groups:
      otelcol:
        patterns:
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/opentelemetry-collector-contrib/*"
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
      testify:
        patterns:
        - "github.com/stretchr/testify"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directories:
      - "/packaging/**/*"
    schedule:
      interval: "weekly"
    groups:
      boto3:
        patterns:
          - "boto3"
      pyyaml:
        patterns:
          - "pyyaml"
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directories:
      - "/packaging/msi/**/*"
      - "/tests/zeroconfig/windows/**/*"
    schedule:
      interval: "weekly"
