---
- name: Converge scenario with custom variables
  hosts: all
  become: no
  vars:
    local_artifact_testing_enabled: true
    splunk_access_token: fake-token
    splunk_ingest_url: https://fake-splunk-ingest.com
    splunk_api_url: https://fake-splunk-api.com
    splunk_hec_url: https://fake-splunk-hec.com
    splunk_hec_token: fake-hec-token
    splunk_otel_collector_version: 0.126.0
    splunk_otel_collector_config: '{{ansible_env.ProgramData}}\Splunk\OpenTelemetry Collector\custom_config.yml'
    splunk_otel_collector_config_source: ./custom_collector_config.yml
    splunk_memory_total_mib: 256
    gomemlimit: 230
    install_fluentd: yes
    splunk_listen_interface: 1.2.3.4
    splunk_fluentd_config: '{{ansible_env.ProgramFiles}}\Splunk\OpenTelemetry Collector\fluentd\custom_config.conf'
    splunk_fluentd_config_source: ./custom_fluentd_config.conf
    splunk_otel_collector_additional_env_vars:
      MY_CUSTOM_VAR1: value1
      MY_CUSTOM_VAR2: value2
      MY_CUSTOM_VAR3: 'value3 with spaces'
    splunk_otel_collector_command_line_args: "--discovery --set=processors.batch.timeout=10s"
    install_splunk_dotnet_auto_instrumentation: true
    splunk_dotnet_auto_instrumentation_version: 1.8.0
    splunk_dotnet_auto_instrumentation_system_wide: true
    splunk_dotnet_auto_instrumentation_environment: test-environment
    splunk_dotnet_auto_instrumentation_service_name: test-service-name
    splunk_dotnet_auto_instrumentation_enable_profiler: true
    splunk_dotnet_auto_instrumentation_enable_profiler_memory: true
    splunk_dotnet_auto_instrumentation_additional_options:
      SPLUNK_DOTNET_VAR1: dotnet-value1
      SPLUNK_DOTNET_VAR2: dotnet-value2
    splunk_otel_auto_instrumentation_resource_attributes: dotnet-tag=dotnet-tag-value
  tasks:
    - name: "Include signalfx.splunk_otel_collector.collector role"
      include_role:
        name: "signalfx.splunk_otel_collector.collector"
