---
- name: Converge scenario with custom variables
  hosts: all
  become: no
  vars:
    splunk_access_token: fake-token
    splunk_ingest_url: https://fake-splunk-ingest.com
    splunk_api_url: https://fake-splunk-api.com
    splunk_hec_url: https://fake-splunk-hec.com
    splunk_hec_token: fake-hec-token
    splunk_otel_collector_version: 0.48.0
    splunk_otel_collector_config: '{{ansible_env.ProgramData}}\Splunk\OpenTelemetry Collector\custom_config.yml'
    splunk_otel_collector_config_source: ./custom_collector_config.yml
    splunk_memory_total_mib: 256
    splunk_ballast_size_mib: 100
    install_fluentd: yes
    splunk_listen_interface: 127.0.0.1
    splunk_fluentd_config: '{{ansible_env.ProgramFiles}}\Splunk\OpenTelemetry Collector\fluentd\custom_config.conf'
    splunk_fluentd_config_source: ./custom_fluentd_config.conf
    splunk_otel_collector_additional_env_vars:
      MY_CUSTOM_VAR1: value1
      MY_CUSTOM_VAR2: value2
    install_signalfx_dotnet_auto_instrumentation: true
    signalfx_dotnet_auto_instrumentation_version: 1.0.0
    signalfx_dotnet_auto_instrumentation_system_wide: true
    signalfx_dotnet_auto_instrumentation_environment: test-environment
    signalfx_dotnet_auto_instrumentation_service_name: test-service-name
    signalfx_dotnet_auto_instrumentation_enable_profiler: true
    signalfx_dotnet_auto_instrumentation_enable_profiler_memory: true
    signalfx_dotnet_auto_instrumentation_global_tags: dotnet-tag:dotnet-tag-value
    signalfx_dotnet_auto_instrumentation_additional_options:
      SIGNALFX_DOTNET_VAR1: dotnet-value1
      SIGNALFX_DOTNET_VAR2: dotnet-value2
  tasks:
    - name: "Include signalfx.splunk_otel_collector.collector role"
      include_role:
        name: "collector"
