receivers:
    filelog:
        include: [ /output/file.log ]

exporters:
    splunk_hec/logs:
        # Splunk HTTP Event Collector token.
        token: "00000000-0000-0000-0000-0000000000000"
        # URL to a Splunk instance to send data to.
        endpoint: "https://splunk:8088/services/collector"
        # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
        source: "output"
        # Splunk index, optional name of the Splunk index targeted.
        index: "main"
        # Maximum HTTP connections to use simultaneously when sending data. Defaults to 100.
        max_connections: 20
        # Whether to disable gzip compression over HTTP. Defaults to false.
        disable_compression: false
        # HTTP timeout when sending data. Defaults to 10s.
        timeout: 10s
        # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
        # For this demo, we use a self-signed certificate on the Splunk docker instance, so this flag is set to true.
        insecure_skip_verify: true
processors:
    batch:
    attributes/add_metadata:
        actions:
            - key: region
              action: insert
              value: "normandy"
            - key: zone
              action: insert
              value: "eu-nor1"

extensions:
    health_check:
        endpoint: 0.0.0.0:13133
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679

service:
    extensions: [ pprof, zpages, health_check ]
    pipelines:
        logs:
            receivers: [ filelog ]
            processors: [ batch, attributes/add_metadata ]
            exporters: [ splunk_hec/logs ]
