---
# defaults file for splunk-otel-collector role vars

# splunk_access_token is REQUIRED variable
splunk_access_token: ""

splunk_realm: us0

splunk_otel_collector_version: latest

# Set this variable to /etc/otel/collector/gateway_config.yaml on linux,
# "Program Files\Splunk\OpenTelemetry Collector\gateway_config.yaml" on Windows
# in order to deploy splunk-otel-collector in gateway mode.
splunk_otel_collector_config: ""

# Set splunk_otel_collector_config_source to copy a custom config from
# a local path to splunk_otel_collector_config on remote hosts
splunk_otel_collector_config_source: ""

# Set splunk_config_override for adding new components to the existing default config.
splunk_config_override: ""

# Set splunk_config_override_list_merge to modify the behavior of splunk_config_override,
# when the hashes to merge contain arrays/lists.
splunk_config_override_list_merge: replace

splunk_service_user: splunk-otel-collector
splunk_service_group: splunk-otel-collector

splunk_memory_total_mib: 512
# 1/3 of memory_mib by default
splunk_ballast_size_mib: ""

splunk_listen_interface: "0.0.0.0"
install_fluentd: false
# Whether to start the services installed by the role (splunk-otel-collector and td-agent).
start_service: true

# Disable setting the official Splunk Debian or RPM repository.
splunk_skip_repo: false

# Explicitly set version of td-agent,
# By default: 3.7.1 for Debian stretch and 4.3.2 for other distros.
td_agent_version: ""

# Default path on Linux: "/etc/otel/collector/fluentd/fluent.conf".
# Default path on Windows: "%ProgramFiles%\Splunk\OpenTelemetry Collector\fluentd\td-agent.conf".
splunk_fluentd_config: ""
splunk_fluentd_config_source: ""

# Default path on Linux: "/usr/lib/splunk-otel-collector/agent-bundle".
# Default path on Windows: "%ProgramFiles%\Splunk\OpenTelemetry Collector\agent-bundle".
splunk_bundle_dir: ""

# Default path on Linux: "/usr/lib/splunk-otel-collector/agent-bundle/run/collectd".
# Default path on Windows: "%ProgramFiles%\Splunk\OpenTelemetry Collector\agent-bundle\run\collectd".
splunk_collectd_dir: ""

# Configure otel collector service to use a proxy
splunk_otel_collector_proxy_http: ""
splunk_otel_collector_proxy_https: ""
splunk_otel_collector_no_proxy: "localhost,127.0.0.1,::1"

install_splunk_otel_auto_instrumentation: false
splunk_otel_auto_instrumentation_version: latest
splunk_otel_auto_instrumentation_ld_so_preload: ""
splunk_otel_auto_instrumentation_java_agent_jar: /usr/lib/splunk-instrumentation/splunk-otel-javaagent.jar
splunk_otel_auto_instrumentation_resource_attributes: ""
splunk_otel_auto_instrumentation_service_name: ""
splunk_otel_auto_instrumentation_generate_service_name: true
splunk_otel_auto_instrumentation_disable_telemetry: false
splunk_otel_auto_instrumentation_enable_profiler: false
splunk_otel_auto_instrumentation_enable_profiler_memory: false
splunk_otel_auto_instrumentation_enable_metrics: false

# Custom environment variables for the collector service
splunk_otel_collector_additional_env_vars: {}

# Configure Auto Instrumentation for .NET
install_signalfx_dotnet_auto_instrumentation: false
signalfx_dotnet_auto_instrumentation_version: latest
signalfx_dotnet_auto_instrumentation_msi_url: ""
signalfx_dotnet_auto_instrumentation_github_token: ""
signalfx_dotnet_auto_instrumentation_system_wide: false
signalfx_dotnet_auto_instrumentation_environment: ""
signalfx_dotnet_auto_instrumentation_service_name: ""
signalfx_dotnet_auto_instrumentation_enable_profiler: false
signalfx_dotnet_auto_instrumentation_enable_profiler_memory: false
signalfx_dotnet_auto_instrumentation_global_tags: ""
signalfx_dotnet_auto_instrumentation_iisreset: true
signalfx_dotnet_auto_instrumentation_additional_options: {}
