---
- name: Verify scenario with auto-instrumentation installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Assert splunk-otel-collector service is running
      ansible.builtin.assert:
        that: ansible_facts.services['splunk-otel-collector.service'].state == 'running'

    - name: Populate package facts
      ansible.builtin.package_facts:

    - name: Get splunk-otel-auto-instrumentation version
      ansible.builtin.set_fact:
        auto_instrumentation_version: "{{ ansible_facts.packages['splunk-otel-auto-instrumentation'][0].version }}"

    - name: Check if splunk-otel-js directory exists
      ansible.builtin.stat:
        path: /usr/lib/splunk-instrumentation/splunk-otel-js
      register: splunk_otel_js_dir

    - name: Check if splunk-otel-js is installed
      ansible.builtin.command: npm ls @splunk/otel
      args:
        chdir: /usr/lib/splunk-instrumentation/splunk-otel-js
      register: npm_ls
      changed_when: npm_ls.rc == 0
      when: splunk_otel_js_dir.stat.exists and splunk_otel_js.stat.isdir is defined and splunk_otel_js_dir.stat.isdir

    - name: Assert /etc/ld.so.preload does not contain path to libsplunk.so
      ansible.builtin.lineinfile:
        line: /usr/lib/splunk-instrumentation/libsplunk.so
        dest: /etc/ld.so.preload
        state: absent
      check_mode: yes
      register: preload
      failed_when: preload is changed

    - name: Check for preload config files
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /usr/lib/splunk-instrumentation/instrumentation.conf
        - /etc/splunk/zeroconfig/java.conf
        - /etc/splunk/zeroconfig/node.conf
        - /etc/splunk/zeroconfig/dotnet.conf
      register: config_files

    - name: Assert preload config files do not exist
      ansible.builtin.assert:
        that: not item.stat.exists
      loop: "{{ config_files.results }}"

    - name: Assert instrumentation config contains path to java agent
      ansible.builtin.lineinfile:
        line: "DefaultEnvironment=\"JAVA_TOOL_OPTIONS=\
              -javaagent:/usr/lib/splunk-instrumentation/splunk-otel-javaagent.jar\""
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: present
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config does not contain NODE_OPTIONS
      ansible.builtin.lineinfile:
        regexp: '.*NODE_OPTIONS.*'
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: absent
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config contains .NET env vars
      ansible.builtin.lineinfile:
        line: "DefaultEnvironment=\"{{ item }}\""
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: present
      check_mode: yes
      register: config
      failed_when: config is changed
      loop:
        - CORECLR_ENABLE_PROFILING=1
        - CORECLR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
        - CORECLR_PROFILER_PATH=/usr/lib/splunk-instrumentation/splunk-otel-dotnet/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so
        - DOTNET_ADDITIONAL_DEPS=/usr/lib/splunk-instrumentation/splunk-otel-dotnet/AdditionalDeps
        - DOTNET_SHARED_STORE=/usr/lib/splunk-instrumentation/splunk-otel-dotnet/store
        - DOTNET_STARTUP_HOOKS=/usr/lib/splunk-instrumentation/splunk-otel-dotnet/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll
        - OTEL_DOTNET_AUTO_HOME=/usr/lib/splunk-instrumentation/splunk-otel-dotnet
        - OTEL_DOTNET_AUTO_PLUGINS=Splunk.OpenTelemetry.AutoInstrumentation.Plugin,Splunk.OpenTelemetry.AutoInstrumentation

    - name: Assert instrumentation config contains OTEL_RESOURCE_ATTRIBUTES
      ansible.builtin.lineinfile:
        line: "DefaultEnvironment=\"OTEL_RESOURCE_ATTRIBUTES=\
              splunk.zc.method=splunk-otel-auto-instrumentation-{{ auto_instrumentation_version }}-systemd\""
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: present
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config does not contain OTEL_SERVICE_NAME
      ansible.builtin.lineinfile:
        regexp: '.*OTEL_SERVICE_NAME.*'
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: absent
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config contains SPLUNK_PROFILER_ENABLED
      ansible.builtin.lineinfile:
        line: DefaultEnvironment="SPLUNK_PROFILER_ENABLED=false"
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: present
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config contains SPLUNK_PROFILER_MEMORY_ENABLED
      ansible.builtin.lineinfile:
        line: DefaultEnvironment="SPLUNK_PROFILER_MEMORY_ENABLED=false"
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: present
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config contains SPLUNK_METRICS_ENABLED
      ansible.builtin.lineinfile:
        line: DefaultEnvironment="SPLUNK_METRICS_ENABLED=false"
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: present
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config does not contain OTEL_EXPORTER_OTLP_ENDPOINT
      ansible.builtin.lineinfile:
        regexp: '.*OTEL_EXPORTER_OTLP_ENDPOINT.*'
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: absent
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config does not contain OTEL_EXPORTER_OTLP_PROTOCOL
      ansible.builtin.lineinfile:
        regexp: '.*OTEL_EXPORTER_OTLP_PROTOCOL.*'
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: absent
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config does not contain OTEL_METRICS_EXPORTER
      ansible.builtin.lineinfile:
        regexp: '.*OTEL_METRICS_EXPORTER.*'
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: absent
      check_mode: yes
      register: config
      failed_when: config is changed

    - name: Assert instrumentation config does not contain OTEL_LOGS_EXPORTER
      ansible.builtin.lineinfile:
        regexp: '.*OTEL_LOGS_EXPORTER.*'
        dest: /usr/lib/systemd/system.conf.d/00-splunk-otel-auto-instrumentation.conf
        state: absent
      check_mode: yes
      register: config
      failed_when: config is changed
