---

- name: Make sure access token is provided
  ansible.builtin.assert:
    that:
      - splunk_access_token
    fail_msg: splunk_access_token variable must be provided

- name: Make sure host OS is supported
  ansible.builtin.assert:
    that: ansible_os_family in ["Debian", "RedHat", "Windows", "Suse"]
    fail_msg: "{{ ansible_os_family }} OS family currently is not supported"

- name: Set Vars based on ansible_os_family
  ansible.builtin.import_tasks: vars.yml

- name: Log deprecation warning when Fluentd is enabled
  debug:
    msg: |
      [DEPRECATION WARNING] Fluentd support has been deprecated and will be removed in a future release.
      Please refer to documentation on how to replace usage: https://github.com/signalfx/splunk-otel-collector/blob/main/docs/deprecations/fluentd-support.md
  when: install_fluentd

- name: Linux deployment
  ansible.builtin.import_tasks: linux_install.yml
  when: ansible_os_family != "Windows"

- name: Windows deployment
  ansible.builtin.import_tasks: win_install.yml
  when: ansible_os_family == "Windows"
