# Custom collector config for test purposes

receivers:
  fluentforward:
    endpoint: 127.0.0.1:8006
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['127.0.0.1:8888']

extensions:
  zpages:
    expvar:
      enabled: true

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}

exporters:
  logging/debug:
    verbosity: detailed
  logging/info:
    verbosity: normal

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter]
      exporters: [logging/info]
    logs:
      receivers: [fluentforward, otlp]
      processors: [memory_limiter]
      exporters: [logging/debug]
