---
- name: Converge scenario without fluentd installation
  hosts: all
  become: yes
  vars:
    splunk_access_token: fake-token
    install_fluentd: no
  tasks:
    - name: "Include splunk_otel_collector"
      include_role:
        name: "splunk_otel_collector"
