receivers:
  signalfxgatewayprometheusremotewrite:
    endpoint: "0.0.0.0:19291"
    path: "/metrics"
    buffer_size: 100
extensions:
  health_check:
    endpoint: 0.0.0.0:8888
processors:
  batch:
exporters:
  signalfx:
    # to configure, see https://github:com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    realm: "${SPLUNK_REALM}"
  # Debug exporter
  # If using version 0.85 or lower of the Collector
  # replace 'debug' with 'logging'
  debug:
    verbosity: Detailed
service:
  #telemetry:
  #  metrics:
  #    address: ":19291"
  pipelines:
    metrics:
      receivers: ["signalfxgatewayprometheusremotewrite"]
      processors: ["batch"]
      exporters: 
        - "logging"
        - "signalfx"
