---
namespace: signalfx
name: splunk_otel_collector
description: Ansible collection for Splunk OpenTelemetry Collector role
version: 0.1.3
readme: README.md
authors:
  - Splunk Inc.
dependencies:
  community.general: "*"
license:
  - Apache-2.0
tags:
  - agent
  - apm
  - collector
  - connector
  - gateway
  - logs
  - metrics
  - observability
  - opentelemetry
  - otel
  - splunk
  - telemetry
  - traces
repository: https://github.com/signalfx/splunk-otel-collector/tree/main/deployments/ansible
build_ignore:
  - contributing
  - molecule
