---
# Ensure a custom system group and user created for Splunk OTel Collector service

- name: Ensure service group created for Splunk Otel Collector
  ansible.builtin.group:
    name: "{{ collector_splunk_service_group }}"
    system: yes

- name: Ensure service user created for Splunk Otel Collector
  ansible.builtin.user:
    name: "{{ collector_splunk_service_user }}"
    group: "{{ collector_splunk_service_group }}"
    system: yes
    shell: /sbin/nologin
    home: /etc/otel/collector

- name: Set Otel Collector config directory
  ansible.builtin.file:
    path: /etc/otel/collector
    state: directory
    owner: "{{ collector_splunk_service_user }}"
    group: "{{ collector_splunk_service_group }}"
    mode: '0755'

- name: Ensure systemd service directory for Splunk Otel Collector exists
  ansible.builtin.file:
    path: /etc/systemd/system/splunk-otel-collector.service.d
    state: directory
    mode: '0755'

- name: Set systemd service owner for Splunk Otel Collector
  ansible.builtin.template:
    src: collector-service-owner.conf.j2
    dest: /etc/systemd/system/splunk-otel-collector.service.d/service-owner.conf
    mode: '644'
  notify: "restart splunk-otel-collector"

- name: Set Otel Collector agent bundle directory
  ansible.builtin.file:
    path: "{{ collector_splunk_bundle_dir }}"
    state: directory
    owner: "{{ collector_splunk_service_user }}"
    group: "{{ collector_splunk_service_group }}"
    recurse: yes
