---
- name: Set default ingest url
  ansible.builtin.set_fact:
    splunk_ingest_url: https://ingest.{{ collector_splunk_realm }}.signalfx.com
  when: splunk_ingest_url is not defined or (splunk_ingest_url | trim) == ""

- name: Set default api url
  ansible.builtin.set_fact:
    splunk_api_url: https://api.{{ collector_splunk_realm }}.signalfx.com
  when: splunk_api_url is not defined or (splunk_api_url | trim) == ""

- name: Set default hec url
  ansible.builtin.set_fact:
    splunk_hec_url: "{{ splunk_ingest_url }}/v1/log"
  when: splunk_hec_url is not defined or (splunk_hec_url | trim) == ""

- name: Set default hec token
  ansible.builtin.set_fact:
    collector_splunk_hec_token: "{{ collector_splunk_access_token }}"
  when: collector_splunk_hec_token is not defined or (collector_splunk_hec_token | trim) == ""
