---
# Install Splunk OpenTelemetry Collector from yum repository

- name: Install setcap via dnf package manager
  ansible.builtin.dnf:
    name: "libcap"
    state: present
    update_cache: yes

- name: Add Splunk OpenTelemetry Collector repo to yum source list
  ansible.builtin.yum_repository:
    name: splunk-otel-collector
    description: Splunk OpenTelemetry Collector Repository
    baseurl: "{{ splunk_repo_base_url }}/otel-collector-rpm/release/$basearch/"
    gpgkey: "{{ splunk_repo_base_url }}/otel-collector-rpm/splunk-B3CD4420.pub"
    gpgcheck: yes
    enabled: yes
  when: not (collector_splunk_skip_repo | bool)

- name: Install Splunk OpenTelemetry Collector via dnf package manager
  ansible.builtin.dnf:
    name: "splunk-otel-collector{% if collector_splunk_otel_collector_version != 'latest' %}\
      -{{ collector_splunk_otel_collector_version }}{% endif %}"
    state: "{% if collector_splunk_otel_collector_version != 'latest' %}present{% else %}latest{% endif %}"
    allow_downgrade: yes
    update_cache: yes
  notify:
    - "restart splunk-otel-collector"
  when: not collector_local_artifact_testing_enabled

- name: Copy Splunk OpenTelemetry Collector RPM artifact to remote machine
  ansible.builtin.copy:
    src: /tmp/rpm-{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}-package
    dest: /etc/otel
    mode: '644'
  register: archive_contents
  when: collector_local_artifact_testing_enabled

- name: Install Splunk OpenTelemetry Collector via local RPM artifact
  ansible.builtin.dnf:
    name: "{{ archive_contents.dest }}"
    disable_gpg_check: true
  notify:
    - "restart splunk-otel-collector"
  when: collector_local_artifact_testing_enabled
