---
# Install Splunk OpenTelemetry Auto Instrumentation from yum repository

- name: Install Splunk OpenTelemetry Auto Instrumentation via yum package manager
  ansible.builtin.dnf:
    name: "splunk-otel-auto-instrumentation{% if collector_splunk_otel_auto_instrumentation_version != 'latest' %}\
      -{{ collector_splunk_otel_auto_instrumentation_version }}{% endif %}"
    state: "{% if collector_splunk_otel_auto_instrumentation_version != 'latest' %}present{% else %}latest{% endif %}"
    allow_downgrade: yes
    update_cache: yes
  register: collector_yum_instrumentation_package
