---
# Install Splunk OpenTelemetry Collector from zypper repository

- name: Install setcap via zypper package manager
  community.general.zypper:
    name: "libcap-progs"
    state: present
    update_cache: yes

- name: Import the Splunk GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ collector_splunk_repo_base_url }}/otel-collector-rpm/splunk-B3CD4420.pub"
  when: not (collector_splunk_skip_repo | bool)

- name: Add Splunk OpenTelemetry Collector repo to zypper source list
  ansible.builtin.template:
    src: collector-zypper.repo.j2
    dest: /etc/zypp/repos.d/splunk-otel-collector.repo
    mode: '644'
  when: not (collector_splunk_skip_repo | bool)

- name: Install Splunk OpenTelemetry Collector via zypper package manager
  community.general.zypper:
    name: "splunk-otel-collector{% if collector_splunk_otel_collector_version != 'latest' %}\
      -{{ collector_splunk_otel_collector_version }}{% endif %}"
    state: "{% if collector_splunk_otel_collector_version != 'latest' %}present{% else %}latest{% endif %}"
    oldpackage: yes
    update_cache: yes
  notify:
    - "restart splunk-otel-collector"
  when: not collector_local_artifact_testing_enabled

- name: Copy Splunk OpenTelemetry Collector RPM artifact to remote machine
  ansible.builtin.copy:
    src: /tmp/rpm-{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}-package
    dest: /etc/otel/
    mode: '644'
  register: collector_archive_contents
  when: collector_local_artifact_testing_enabled

- name: Install Splunk OpenTelemetry Collector via local RPM artifact
  community.general.zypper:
    name: "{{ collector_archive_contents.dest }}"
    disable_gpg_check: true
  notify:
    - "restart splunk-otel-collector"
  when: collector_local_artifact_testing_enabled
