# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: 'breaking'

# The name of the component, or a single word describing the area of concern, (e.g. crosslink)
component: configserver

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: The local config server endpoint is now disabled by default.

# One or more tracking issues related to the change
issues: [6806]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  For troubleshooting the Splunk OpenTelemetry Collector provides a sensitive value-redacting, local config server listening at
  `http://localhost:55554/debug/configz/effective`. This endpoint is being phased out in favor of the `expvar` entry under the
  `zpages`, see [previous release changelog](https://github.com/signalfx/splunk-otel-collector/blob/b44d72b60f92c0de165cdbafc90d288313f959dd/CHANGELOG.md?plain=1#L159)
  for information about how to use and configure the new endpoint. If you still need the old endpoint
  set the `SPLUNK_DEBUG_CONFIG_SERVER` environment variable to `true`.
