# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: 'enhancement'ent

# The name of the component, or a single word describing the area of concern, (e.g. crosslink)
component: Splunk_TA_otel

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: "Change internal/settings log format for Splunk TA for OpenTelemetry"

# One or more tracking issues related to the change
issues: [6749]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  The formatting of the internal/settings log was changed to correctly report log level when the collector is running
  as the Splunk TA for OpenTelemetry. Related to change [6748](https://github.com/signalfx/splunk-otel-collector/pull/6748).
