# This action requires that any PR targeting the main branch should add a
# yaml file to the ./.chloggen/ directory. If a CHANGELOG entry is not required,
# or if performing maintenance on the Changelog, add either \"[chore]\" to the title of
# the pull request or add the \"Skip Changelog\" label to disable this action.

name: changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5
        with:
          go-version: "~1.25.0"
          check-latest: true
      - name: Cache Go
        id: go-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: changelog-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Ensure no changes to the CHANGELOG
        run: |
          if [[ "$(git diff --name-only "$(git merge-base origin/main ${{ github.event.pull_request.head.sha }})" ${{ github.event.pull_request.head.sha }} ./CHANGELOG.md)" ]]
          then
            echo "The CHANGELOG should not be directly modified."
            echo "Please add a .yaml file to the ./.chloggen/ directory."
            echo "Run make chlog-new to add a new changelog file."
            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
            false
          else
            echo "The CHANGELOG was not modified."
          fi

      - name: Ensure ./.chloggen/*.yaml addition(s)
        run: |
          if [[ 1 -gt "$(git diff --diff-filter=A --name-only "$(git merge-base origin/main ${{ github.event.pull_request.head.sha }})" ${{ github.event.pull_request.head.sha }} ./.chloggen | grep -c \\.yaml)" ]]
          then
            echo "No changelog entry was added to the ./.chloggen/ directory."
            echo "Please add a .yaml file to the ./.chloggen/ directory."
            echo "Run make chlog-new to add a new changelog file."
            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
            false
          else
            echo "A changelog entry was added to the ./.chloggen/ directory."
          fi

      - name: Validate ./.chloggen/*.yaml changes
        run: |
          make install-tools
          make chlog-validate \
            || { echo "New ./.chloggen/*.yaml file failed validation."; exit 1; }

      # In order to validate any links in the yaml file, render the config to markdown
      - name: Render .chloggen changelog entries
        run: make chlog-preview > changelog_preview.md
      - name: Link Checker
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.title, '[chore]')}}
        id: lychee
        uses: lycheeverse/lychee-action@74c50ae9cb26a12ef66ad5769546fe0848ae9596 # f613c4a64e50d792e0b31ec34bbcbba12263c6a6
        with:
          args: "--verbose --no-progress ./changelog_preview.md --config .lychee.toml"
          failIfEmpty: false
