name: darwin-test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/darwin-test.yml'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'tests/**'
      - 'Makefile'
      - 'Makefile.Common'
      - 'go.mod'
      - 'go.sum'
      - '!**.md'
      - '!internal/buildscripts/**'

env:
  GO_VERSION: '1.22.6'

concurrency:
  group: darwin-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  darwin-test:
    name: darwin-test
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        # The "macos-13-xlarge" runner is arm64: https://github.com/actions/runner-images/issues/8439
        OS: [ "macos-12", "macos-13", "macos-13-xlarge", "macos-14" ]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '**/go.sum'

      - run: go env -w CGO_ENABLED=0

      - name: Install golang dependency
        run: make install-tools

      - name: Unit tests with coverage
        run: make test-with-cover

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results-${{ matrix.OS }}
          path: ./coverage.html
