name: darwin-test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/darwin-test.yml'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'tests/**'
      - 'Makefile'
      - 'Makefile.Common'
      - 'go.mod'
      - 'go.sum'
      - '!**.md'
      - '!packaging/**'

env:
  GO_VERSION: 1.23.7

concurrency:
  group: darwin-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  darwin-test:
    name: darwin-test
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        # The "macos-13-xlarge" runner is arm64: https://github.com/actions/runner-images/issues/8439
        OS: [ "macos-13", "macos-13-xlarge", "macos-14", "macos-15" ]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '**/go.sum'

      - run: go env -w CGO_ENABLED=0

      - name: Unit tests
        run: |
          set -o pipefail
          make install-tools
          mkdir -p unit-test-results-darwin/junit
          trap "go-junit-report  -set-exit-code < unit-test-results-darwin/go-unit-tests.out > unit-test-results-darwin/junit/results.xml" EXIT
          make for-all CMD="make test-without-race" | tee unit-test-results-darwin/go-unit-tests.out

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-darwin
          path: ./unit-test-results-darwin

      - name: bundle.d
        run: |
          make bundle.d
          if ! git diff --exit-code; then
            echo "Discovery bundle.d config has changed. Run 'make bundle.d' and push the changes or ensure correct .tmpl updated."
            exit 1
          fi