name: darwin-test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: 1.23.8

concurrency:
  group: darwin-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  darwin-test:
    name: darwin-test
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        # The "macos-13-xlarge" runner is arm64: https://github.com/actions/runner-images/issues/8439
        OS: [ "macos-13", "macos-13-xlarge", "macos-14", "macos-15" ]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '**/go.sum'

      - run: go env -w CGO_ENABLED=0

      - name: Unit tests
        run: |
          set -o pipefail
          make install-tools
          mkdir -p unit-test-results-${{ matrix.OS }}/junit
          trap "go-junit-report  -set-exit-code < unit-test-results-${{ matrix.OS }}/go-unit-tests.out > unit-test-results-${{ matrix.OS }}/junit/results.xml" EXIT
          make gotest-cover-without-race | tee unit-test-results-${{ matrix.OS }}/go-unit-tests.out

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-${{ matrix.OS }}
          path: ./unit-test-results-${{ matrix.OS }}

      - name: Upload coverage report
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # 5.4.2
        with:
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: bundle.d
        run: |
          make bundle.d
          if ! git diff --exit-code; then
            echo "Discovery bundle.d config has changed. Run 'make bundle.d' and push the changes or ensure correct .tmpl updated."
            exit 1
          fi