on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.1
        with:
          args: --accept 200,429 --exclude "my.host" --exclude "file://*" --exclude "api.*.signalfx.com" --exclude "ingest.*.signalfx.com" --exclude "splunk.jfrog.io.*basearch" --exclude "localhost:*" --exclude "127.*:*" -v -n './*.md' './**/*.md'
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
