name: compile

on:
  workflow_call:
    inputs:
      SYS_BINARY:
        required: true
        type: string

env:
  GO_VERSION: 1.25.7

jobs:
  compile:
    name: compile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-environment

      - name: Generate OBI BPF files
        if: contains(inputs.SYS_BINARY, 'linux')
        uses: ./.github/actions/generate-obi-bpf

      - name: Build Collector
        run: |
          make ${{ inputs.SYS_BINARY }}

      - name: Uploading binaries
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.SYS_BINARY }}
          path: |
            ./bin/*
