name: shellcheck
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-24.04
    env:
      VERSION: v0.10.0
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v6
      - name: shellcheck github workflow scripts
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        env:
          SHELLCHECK_OPTS: -x -e SC2059 -e SC2086
        with:
          ignore_paths: >-
            .github/workflows/scripts/win-required-ports.ps1
            .github/workflows/scripts/win-test-services.ps1
            .github/workflows/scripts/win-test-support-bundle.ps1
          scandir: ".github/workflows/scripts"
          severity: warning
          version: ${{ env.VERSION }}
      - name: shellcheck gitlab workflow scripts
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        env:
          SHELLCHECK_OPTS: -x -e SC2059 -e SC2086
        with:
          scandir: ".gitlab/"
          severity: warning
          version: ${{ env.VERSION }}
      - name: shellcheck scripted inputs receiver scripts
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        env:
          SHELLCHECK_OPTS: -x -e SC2059 -e SC2086
        with:
          scandir: "./internal/receiver/scriptedinputsreceiver/scripts"
          severity: warning
          version: ${{ env.VERSION }}
